import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Bold,
  Code2,
  FileCode,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Image,
  Italic,
  Link2,
  Link2Off,
  List,
  ListOrdered,
  PaintBucket,
  Pilcrow,
  Quote,
  Strikethrough,
  Subscript,
  Superscript,
  Underline,
  Undo2,
  Redo2
} from 'lucide-react';


export const Icons = {
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  bg: PaintBucket,
  blockquote: Quote,
  bold: Bold,
  code: Code2,
  codeblock: FileCode,
  h1: Heading1,
  h2: Heading2,
  h3: Heading3,
  h4: Heading4,
  h5: Heading5,
  h6: Heading6,
  image: Image,
  italic: Italic,
  link: Link2,
  ol: ListOrdered,
  paragraph: Pilcrow,
  strikethrough: Strikethrough,
  subscript: Subscript,
  superscript: Superscript,
  ul: List,
  underline: Underline,
  unlink: Link2Off,
  redo: Redo2,
  undo: Undo2,
};
